
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Marco Antonio
 */
public class practica2 extends javax.swing.JFrame {
    DefaultListModel lista = new DefaultListModel();
      private int index = -1; //esto es para eliminar


    /**
     * Creates new form practica2
     */
    public practica2() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Txtnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtEdad = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnordenar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnborrarlista = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listanombreyedad = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 500));
        setResizable(false);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jPanel7.setLayout(new java.awt.GridLayout(10, 1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 3, 18)); // NOI18N
        jLabel2.setText("Escribe el nombre");
        jPanel7.add(jLabel2);

        Txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtnombreKeyTyped(evt);
            }
        });
        jPanel7.add(Txtnombre);

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 3, 18)); // NOI18N
        jLabel3.setText("Escribe la edad");
        jLabel3.setPreferredSize(new java.awt.Dimension(38, 15));
        jPanel7.add(jLabel3);

        TxtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtEdadKeyTyped(evt);
            }
        });
        jPanel7.add(TxtEdad);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.add(jLabel1);

        btnAgregar.setFont(new java.awt.Font("Segoe UI Historic", 3, 18)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel7.add(btnAgregar);

        btnordenar.setFont(new java.awt.Font("Segoe UI Historic", 3, 18)); // NOI18N
        btnordenar.setText("ordenar");
        btnordenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnordenarActionPerformed(evt);
            }
        });
        jPanel7.add(btnordenar);

        BtnEliminar.setFont(new java.awt.Font("Segoe UI Historic", 3, 18)); // NOI18N
        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });
        jPanel7.add(BtnEliminar);

        btnSalir.setFont(new java.awt.Font("Segoe UI Historic", 3, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel7.add(btnSalir);

        btnborrarlista.setFont(new java.awt.Font("Segoe UI Historic", 3, 18)); // NOI18N
        btnborrarlista.setText("borrar lista");
        btnborrarlista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarlistaActionPerformed(evt);
            }
        });
        jPanel7.add(btnborrarlista);

        jPanel1.add(jPanel7);

        jPanel6.setLayout(new java.awt.GridLayout(1, 1));

        jScrollPane1.setViewportView(listanombreyedad);

        jPanel6.add(jScrollPane1);

        jPanel1.add(jPanel6);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setForeground(new java.awt.Color(0, 255, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(565, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(565, 20));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 656, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setPreferredSize(new java.awt.Dimension(20, 537));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setPreferredSize(new java.awt.Dimension(20, 537));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void TxtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtnombreKeyTyped
        // TODO add your handling code here:
        char letra = evt.getKeyChar();
       
        //JOptionPane.showMessageDialog(null, letra);
        if ((letra >= 65 && letra <= 90)|| (letra >= 97 && letra <= 122) ||(letra ==10) ||(letra == 8)){
            if(letra ==10){
                agregarTODO();
            }
            if(letra == 8){
                eliminar();
            }
            
        }else{
          evt.consume();
          JOptionPane.showMessageDialog(null, "Error, solo letras");
        }
    
    }//GEN-LAST:event_TxtnombreKeyTyped

    private void TxtEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtEdadKeyTyped
     int letra = evt.getKeyChar();
       
        //JOptionPane.showMessageDialog(null, letra);
        if ((letra >= 48 && letra <= 57) ||(letra ==10) ||(letra == 8)){
            if(letra ==10){
                agregarTODO();
            }
            if(letra == 8){
                eliminar();
            }
            
        }else{
          evt.consume();
          JOptionPane.showMessageDialog(null, "Error, solo numeros");
        }
    }//GEN-LAST:event_TxtEdadKeyTyped

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        agregarTODO();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        // TODO add your handling code here:
        
        eliminar();
    }//GEN-LAST:event_BtnEliminarActionPerformed

    private void btnordenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnordenarActionPerformed
        // TODO add your handling code here:
        
          String [] num =new String[lista.size()];
       
        for (int i = 0; i < lista.size(); i++) {
            num[i] = (String) lista.getElementAt(i);
        }
        String aux = "";
        int a = 0;
        int b = 0;
        for (int i = 0; i < num.length; i++) {
         for (int j = 0; j < num.length-1; j++) {
           a = num[j].codePointAt(0);
            b = num[j+1].codePointAt(0);
            if(a < b){
                aux = num[j+1];
                num[j+1]= num[j];
                num[j] = aux;
                
            }
        }
        }
        for (int i = 0; i < num.length; i++) {
            //System.out.println(num[i]);
             lista.addElement(num[i]);
             listanombreyedad.setModel(lista);
            
        }
        
        
    }//GEN-LAST:event_btnordenarActionPerformed

    private void btnborrarlistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarlistaActionPerformed
        // TODO add your handling code here:
        lista.clear();
    }//GEN-LAST:event_btnborrarlistaActionPerformed
 private void eliminar(){
    
     // TODO add your handling code here:\
        index = listanombreyedad.getSelectedIndex();
        if(index != -1){
            lista.removeElementAt(index);
        }else{
            
      JOptionPane.showMessageDialog(null, "lista vacia no has escogido ningun elemento");
            
    
    }
    
 }
    
    
    
    private  void agregarTODO(){
     
         if(Txtnombre.getText().length()==0||TxtEdad.getText().length()==0){
        JOptionPane.showMessageDialog(null, "error escribe NOMBRE O EDAD");
    }else{

         String nombre=Txtnombre.getText();
        int edad = Integer.parseInt(TxtEdad.getText());
        nombre = nombre +","+Integer.toString(edad);
        lista.addElement(nombre);
        listanombreyedad.setModel(lista);
       TxtEdad.setText("");
        Txtnombre.setText("");
        
    }
    }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(practica2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(practica2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(practica2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(practica2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new practica2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JTextField TxtEdad;
    private javax.swing.JTextField Txtnombre;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnborrarlista;
    private javax.swing.JButton btnordenar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listanombreyedad;
    // End of variables declaration//GEN-END:variables

    private int num(int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
