/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newpackage;

import java.beans.PropertyVetoException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Marco Antonio
 */
public class principal extends javax.swing.JFrame {
   public boolean ventanacrear = false;
    private crear crear;
   private Mostrar mostrar;

   
    public principal() {
        initComponents();
       
     
        setLocationRelativeTo(null);
        

               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        mnuACrear = new javax.swing.JMenu();
        mnuCrear = new javax.swing.JMenuItem();
        Mnumostrar = new javax.swing.JMenuItem();
        mnuAsalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuACrear.setMnemonic('f');
        mnuACrear.setText("Archivo");
        mnuACrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuACrearActionPerformed(evt);
            }
        });

        mnuCrear.setMnemonic('o');
        mnuCrear.setText("Crear Archivo");
        mnuCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCrearActionPerformed(evt);
            }
        });
        mnuACrear.add(mnuCrear);

        Mnumostrar.setMnemonic('s');
        Mnumostrar.setText("Mostrar datos del archivo");
        Mnumostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnumostrarActionPerformed(evt);
            }
        });
        mnuACrear.add(Mnumostrar);

        mnuAsalir.setMnemonic('x');
        mnuAsalir.setText("Salir");
        mnuAsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAsalirActionPerformed(evt);
            }
        });
        mnuACrear.add(mnuAsalir);

        menuBar.add(mnuACrear);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuAsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAsalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuAsalirActionPerformed
   
    private void mostrarformulario(){
    if(crear == null|| crear.isClosed()){
    crear = new crear();
    Escritorio.add(crear);
    crear.setVisible(null);
   
    }else{
        crear.setVisible(null);
        crear.toFront();
    
    }
    }
    
  
    private void mnuACrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuACrearActionPerformed
        // TODO add your handling code here:
    
        
        
    }//GEN-LAST:event_mnuACrearActionPerformed
   
 
    
    private void mnuCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCrearActionPerformed
        // TODO add your handling code here:
       
            crear c = new crear ();  
        Escritorio.add(c);
        c.setVisible(true);
        ventanacrear = true;
        
    }//GEN-LAST:event_mnuCrearActionPerformed

    private void MnumostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnumostrarActionPerformed
        // TODO add your handling code here:
          
       if (mostrar == null || mostrar.isClosed()){
           try {
               mostrar = new Mostrar();
           } catch (IOException ex) {
               Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
           }
           Escritorio.add(mostrar);
           mostrar.setVisible(true);
       }else{
           try {
               crear.setSelected(true); 
               crear.toFront();
           } catch (PropertyVetoException ex) {
               Logger.getLogger(principal.class.getName()).log(Level.SEVERE, null, ex);
           }
          
           
       }
    }//GEN-LAST:event_MnumostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem Mnumostrar;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuACrear;
    private javax.swing.JMenuItem mnuAsalir;
    private javax.swing.JMenuItem mnuCrear;
    // End of variables declaration//GEN-END:variables

}
        
