/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clase;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Marco Antonio
 */
public class lista extends javax.swing.JFrame {
    DefaultListModel lista = new DefaultListModel();
    private int index = -1; //esto es para eliminar

    /**
     * Creates new form lista
     */
    public lista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnumero = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        btnagregr = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnordenar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btnborrarlista = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listanumero = new javax.swing.JList<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 400));
        setResizable(false);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jPanel6.setLayout(new java.awt.GridLayout(1, 2));

        jPanel8.setLayout(new java.awt.GridLayout(3, 1));

        jPanel9.setLayout(new java.awt.GridLayout(2, 1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 3, 18)); // NOI18N
        jLabel1.setText("Escribe un numero");
        jPanel9.add(jLabel1);

        txtnumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnumeroKeyTyped(evt);
            }
        });
        jPanel9.add(txtnumero);

        jPanel8.add(jPanel9);

        jPanel10.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 193, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel10);

        jPanel11.setLayout(new java.awt.GridLayout(5, 1));

        btnagregr.setFont(new java.awt.Font("Segoe UI Historic", 3, 18)); // NOI18N
        btnagregr.setText("agregar");
        btnagregr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregrActionPerformed(evt);
            }
        });
        jPanel11.add(btnagregr);

        btnEliminar.setFont(new java.awt.Font("Segoe UI Historic", 3, 18)); // NOI18N
        btnEliminar.setText("eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel11.add(btnEliminar);

        btnordenar.setFont(new java.awt.Font("Segoe UI Historic", 3, 18)); // NOI18N
        btnordenar.setText("ordenar");
        btnordenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnordenarActionPerformed(evt);
            }
        });
        jPanel11.add(btnordenar);

        btnsalir.setFont(new java.awt.Font("Segoe UI Historic", 3, 18)); // NOI18N
        btnsalir.setText("salir");
        jPanel11.add(btnsalir);

        btnborrarlista.setFont(new java.awt.Font("Segoe UI Historic", 3, 18)); // NOI18N
        btnborrarlista.setText("borrar lista");
        btnborrarlista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarlistaActionPerformed(evt);
            }
        });
        jPanel11.add(btnborrarlista);

        jPanel8.add(jPanel11);

        jPanel6.add(jPanel8);

        jPanel7.setLayout(new java.awt.GridLayout(1, 1));

        jScrollPane1.setViewportView(listanumero);

        jPanel7.add(jScrollPane1);

        jPanel6.add(jPanel7);

        jPanel1.add(jPanel6);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(592, 20));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 607, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(20, 274));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnumeroKeyTyped
        // TODO add your handling code here:
       int letra = evt.getKeyChar();
       
        //JOptionPane.showMessageDialog(null, letra);
        if ((letra >= 48 && letra <= 57) ||(letra ==10) ||(letra == 0)){
            if(letra ==10){
                agregar();
            }
            if(letra == 8){
                eliminar();
            }
            
        }else{
          evt.consume();
          JOptionPane.showMessageDialog(null, "Error, solo numeros");
        }
    }//GEN-LAST:event_txtnumeroKeyTyped

    private void btnagregrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregrActionPerformed
        // TODO add your handling code here:
       agregar();
    }//GEN-LAST:event_btnagregrActionPerformed

    private  void agregar(){
         if(txtnumero.getText().length()==0){
        JOptionPane.showMessageDialog(null, "error escribe un numero");
    }else{

    
        int numero = Integer.parseInt(txtnumero.getText());
        lista.addElement(numero);
        listanumero.setModel(lista);
        txtnumero.setText("");
}
    
    
    
    
    
    }
    
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
      eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnordenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnordenarActionPerformed
        // TODO add your handling code here:
        //System.out.println(lista.size());
        int [] num =new int[lista.size()];
       
        for (int i = 0; i < lista.size(); i++) {
            num[1] = (int) lista.getElementAt(1);
        }
        int aux = 0;
        for (int i = 0; i < num.length; i++) {
         for (int j = 0; j < num.length-1; j++) {
            if(num[j] < num (j+1)){
                aux = num[j+1];
                num[j+1]= num[j];
                num[j] = aux;
                
            }
        }
        }
        for (int i = 0; i < num.length; i++) {
            //System.out.println(num[i]);
             lista.addElement(num[i]);
             listanumero.setModel(lista);
            
        }
            
            
        

    }//GEN-LAST:event_btnordenarActionPerformed

    private void btnborrarlistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarlistaActionPerformed
        // TODO add your handling code here:
        lista.clear();
    }//GEN-LAST:event_btnborrarlistaActionPerformed
    private void eliminar(){
    
     // TODO add your handling code here:\
        index = listanumero.getSelectedIndex();
        if(index != -1){
            lista.removeElementAt(index);
        }else{
            
      JOptionPane.showMessageDialog(null, "lista vacia no has escogido ningun elemento");
            
    
    }
    
    
    
    
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnagregr;
    private javax.swing.JButton btnborrarlista;
    private javax.swing.JButton btnordenar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listanumero;
    private javax.swing.JTextField txtnumero;
    // End of variables declaration//GEN-END:variables

    private int num(int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
